### ISSUE TITLE
How to add a new compression type?

### ISSUE THREAD

**Issue by Elvisass** [Vadim07/AssetStudio#18]
Hi,

I'm not really familiar with C# and Unity's low-level details or anything related to cracking, but I'm still trying to dig into the models of the new Arknights game (Endfield). When attempting to open the game directory, I got a `Unsupported compression type 5` error. It seems to be the exception thrown in `BundleFile.ReadBlocks()` in `AssetStudio/BundleFile.cs` line 398.

I've no idea where the enum values for CompressionType come from. Are they derived from Unity's documentation, or something obtained through reverse engineering?

I want to try adding some decompression logic but idk what the algorithm is for "type 5"...

**Comment by aelurum** [comment]
Hi
Well, since you are not familiar with c#, just use the latest build of [Razmoth's Studio](https://github.com/RazTools/Studio/actions/runs/6854735096).
Support for this game has already been added there.
But if you are interested, akendfield uses a slightly modified lz4 compression, and some other unity classes are also modified there.

**Comment by Elvisass** [comment]
> Hi Well, since you are not familiar with c#, just use the latest build of [Razmoth's Studio](https://github.com/RazTools/Studio/actions/runs/6854735096). Support for this game has already been added there. But if you are interested, akendfield uses a slightly modified lz4 compression, and some other unity classes are also modified there.

thx XD
I'll take a look at that codes and try to debug and export
