### ISSUE TITLE
path IDs in exported file name

### ISSUE THREAD

**Issue by portablevampire** [Vadim07/AssetStudio#25]
hello, me again, sorry i hate to request another feature when i've already got another enhancement request open, but i'm wondering if it might be possible to implement an option to include the path ID of exported assets in their filename? i know it lists path IDs of exported objects if you generate an assets.xml file, but it can be kind of hard to match up the asset listed in the xml file to its exported file especially when a lot of monobehavior objects have the same name. If this is something that can be done in addition to the group assets by source file name option, that would be ideal.

this would be really useful in saving me time—the path IDs are pretty important for a lot of the asset mining i do, and being able to export assets with path IDs somewhere in the filename would allow me to write python scripts that would speed up the process of looking through these assets significantly. even if its just added to the cli version only that would be fine

**Comment by mayfrogs** [comment]
i would take care of this one myself and spare you the trouble, because after a while rooting around in the source code i'm pretty sure i know what code to add and where to accomplish this, (albeit rudimentarily) but even with all the necessary SDKs installed i can't seem to figure out how to build it without getting loads of type/namespace and dependency errors. (and that's BEFORE editing the source code, so it's not like i messed up the code anywhere.) which i realize fully exposes how much i am out of my depth when it comes to C# projects (my coding experience is currently limited to javascript and python, so while I can pretty easily figure out where to modify the code itself based on similarities to other languages, it seems like actually running/compiling it is not quite as simple as hitting run in IDLE, and is perhaps beyond my capabilities) but i say all this to illustrate how, while this is probably an easy thing to implement at least rudimentarily, i am evidently absolutely not the person to do it.

**Comment by portablevampire** [comment]
I thought I'd take care of this myself and spare you the trouble, because looking through the source code, I'm pretty certain I know exactly what part of the code to modify and how in order to accomplish this, but I'm woefully inexperienced with C# projects and VSCode, and even with all of the necessary SDKs (yes, including FBX and all of the different .NET SDK versions) I can't seem to figure out how to build the thing without getting hundreds and hundreds of namespace errors. It's a little frustrating that despite being able to figure out how to edit the code to get this to work, I get stuck at building it. My coding experience is mostly with Python, so anything more complicated than hitting "Run Module" in IDLE has me scratching my head.

If you're not interested in adding this, then I would appreciate at least a nudge in the right direction with regards to how to build this myself without namespace errors in the hundreds (I've got about 495 errors) so that I could at least take care of it myself that would be appreciated.

**Comment by aelurum** [comment]
Hi
Yeah, I will add such option, you are not the first who wants it.
In fact, even the first version of AssetStudio that I modified ([AssetStudio v0.14.38 mod](https://github.com/aelurum/AssetStudio/releases/tag/v0.14.38.5)) had it, but only for images, and yes, it's pretty outdated.

As for VSCode, I didn't try to work with it.
As you can see in the readme, you need Visual Studio 2022.
And then there shouldn't be any problems (https://github.com/aelurum/AssetStudio/discussions/26)

**Comment by mayfrogs** [comment]
I did try Visual Studio 2022 as well but didn't have luck there either, not sure why, but I'm sure there's something obvious I'm overlooking. I'm not very good at working with Visual Studio

But anyway thank you, having this feature will be very useful so I appreciate it a lot.
