### ISSUE TITLE
v0.17.0 release binaries

### ISSUE THREAD

**Issue by HeCorr** [Vadim07/AssetStudio#4]
Hello! Now that you've [committed a new version](https://github.com/aelurum/AssetStudio/commit/bb9ea7d86b9f183ce0741c6463630f55c276904b), do you think you could publish a release with the binaries so people can download it?

The [AppVeyor link](https://ci.appveyor.com/project/aelurum/assetstudio-mod/build/artifacts) isn't working at the moment.

Thanks!

**Comment by aelurum** [comment]
Hi
Yeah, release should be soon
There are a few more changes that I want to make, but I think I'll publish a release version before the end of the month

The old AppVeyor link doesn't work because the project name has changed
So the new link is [https://ci.appveyor.com/project/aelurum/assetstudiomod/build/artifacts](https://ci.appveyor.com/project/aelurum/assetstudiomod/build/artifacts)

**Comment by HeCorr** [comment]
ahh, fair enough. thank you!
