### ISSUE TITLE
Incomplete asset dumping

### ISSUE THREAD

**Issue by JunkBeat** [Vadim07/AssetStudio#55]
AssetStudio can display a list of all assets, but it correctly dumps only certain asset types such as MonoBehaviour, Texture2D, AudioClip. If you select any other type, the following will be displayed:
```
{
    "m_PathID": 509,
    "type": 82,
    "byteSize": 228
}
```

Is it possible to improve this? If you manage to create a full dumping, it will be awesome.

**Comment by aelurum** [comment]
**In short: no.**

AssetStudioMod can display full dump of any asset if a file includes type tree info.
In other cases, the dump simply displays manually parsed asset fields that AssetStudio itself uses.
(In fact, this is already an improvement, since the original Studio just doesn't show dumps for such assets)

Theoretically, the desired behavior would be possible if AssetStudioMod used [tpk](https://github.com/AssetRipper/Tpk) files (like AssetRipper, UABEA, UnityPy(soon), etc.) that already contain type tree info of each official Unity version.
But this approach has its own limitations, e.g. it will become harder to support assets with modified type tree fields, which is actually not such a rare case.
So I don't plan to add tpk support to AssetStudioMod.

I can suggest using [AssetRipper](https://github.com/AssetRipper/AssetRipper/) / [UABEA](https://github.com/nesrak1/UABEA) / [UABEANext](https://github.com/nesrak1/UABEANext)*(uabea but has a bit similar GUI to AssetStudio)* if you want to see dumps of assets without attached type tree info.
